### ISSUE TITLE
"utility.jl"Not found in the file

### ISSUE THREAD

**Issue by Alanw-git** [rockstaedt/DecentralOPF.jl#1]
Dear author, I have seen your article and the ADMM solution framework. I am very encouraged and hope to learn the latest knowledge. However, when I ran the code, due to the lack of utility.jl files, it was impossible to optimize the operation as a whole. Can you share it in GitHub? Thank you!

**Comment by rockstaedt** [comment]
Hi! :) Thanks for reaching out! I'll have a look at this and will get back at you!

**Comment by rockstaedt** [comment]
@Alanw-git I added some information on how you can get started, see the README.md. In my opinion, you do not need a utility file. Can you check this?

**Comment by Alanw-git** [comment]
Yeah,Most code can run normally, only like like(https://github.com/rockstaedt/DecentralOPF.jl/tree/main/approaches/3_dispatch%20ADMM)/ include（"utility.jl"）sentence, but there is no impact on the overall learning, thank you very much for your enthusiastic reply！

**Comment by rockstaedt** [comment]
Oh yes! Alright! Didn't think about the approaches... I just included these scripts to show other people how I developed the model. I will have a look at this 👍🏼
